services:
  db:
    container_name: Noto
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend


  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: >
      sh -c "redis-server --requirepass $REDIS_PASSWORD"
    volumes:
      - redis_data:/data
    networks:
      - backend


volumes:
  postgres_data:
  redis_data:

networks:
  backend:
